micronaut:
  application:
    name: weather
  io:
    watch:
      paths: src/main
      restart: true
  caches.weather.expire-after-write: 180s
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:static
    webjars:
      enabled: true
      paths: classpath:META-INF/resources/webjars
      mapping: /webjars/**
jackson:
  serialization:
    writeDatesAsTimestamps: false
    indentOutput: false
  modules:
    - javaTimeModule
    - kotlinModule
