micronaut:
  application:
    name: weather
  caches.weather.expire-after-write: 180s
jackson:
  serialization:
    writeDatesAsTimestamps: false
    indentOutput: true
  modules:
    - javaTimeModule
    - kotlinModule
